os: linux
dist: xenial
language: node_js

jobs:
  include:
    - language: node_js
      node_js:
        - "12"
      addons:
        chrome: stable
      install:
        - npm install
        - npm install codecov -g
      script:
        - npm run lint:ui
        - npm run test:ui
        - npm run build:ui
      after_success:
        - codecov

    - language: python
      python:
        - 3.8
      install:
        - pip install -e .
        - pip install -r requirements-dev.txt
        - python setup.py develop
      script:
        - python -m mypy nbtutor
        - python -m flake8 nbtutor setup.py
        - python -m pytest --cov --cov-report=term-missing -vv tests nbtutor
      after_success:
        - bash <(curl -s https://codecov.io/bash)
