os: linux
dist: xenial
language: node_js

jobs:
  include:
    - language: node_js
      node_js:
        - 12
      addons:
        chrome: stable
      install:
        - npm install
        - npm install codecov -g
      script:
        - npm run lint:ui
        - npm run test:ui
        - npm run build:ui
      after_success:
        - codecov

    - language: python
      python:
        - 3.8
      install:
        - python -m pip install nox mypy flake8
      script:
        - python -m mypy nbtutor
        - python -m flake8 nbtutor setup.py noxfile.py
        - nox --sessions test
        - python -m pip install -e .
        - jupyter nbextension install --overwrite --sys-prefix --py nbtutor
        - jupyter nbextension enable nbtutor --py --sys-prefix
      after_success:
        - bash <(curl -s https://codecov.io/bash)

addons:
  apt:
    sources:
        - deadsnakes
    packages:
        - python3.7
        - python3.9
        - python3.10
