matrix:
  include:
    - language: node_js
      node_js:
        - "12"
      addons:
        chrome: stable
      install:
        - npm install
      script:
        - npm run lint:ui
        - npm run test:ui
        - npm run build:ui

    - language: python
      python:
        - 3.8
      install:
        - pip install -e .
        - python setup.py test
      script:
        - python -m mypy nbtutor
        - python -m flake8 nbtutor setup.py
        - python -m pytest --cov --cov-report=term-missing -vv tests nbtutor

after_success:
  - bash < (curl -s https://codecov.io/bash)
