name: nbtutor
channels:
  - conda-forge
  - defaults
dependencies:
  - anaconda-client
  - coverage
  - flake8
  - isort
  - nodejs
  - notebook
  - pytest
  - pytest-cov
  - python
  - requests
  - sphinx
