name: Python

on:
  push:
    branches:
      - main
      - "release/**"
  pull_request:
    branches:
      - main
      - "release/**"

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nox mypy flake8 codecov

      - name: Lint
        run: |
          python -m mypy nbtutor
          python -m flake8 nbtutor setup.py noxfile.py

      - name: Test
        run: |
          nox --sessions test-${{ matrix.python-version }}
          codecov -t ${{ secrets.CODECOV_TOKEN }}

      - name: Activate
        run: |
          python -m pip install -e .
          jupyter nbextension install --overwrite --sys-prefix --py nbtutor
          jupyter nbextension enable nbtutor --py --sys-prefix
